# Карчевский Андрей, ДПИ25-1

## Разминка 1
Сгенерируем массив `arr` размера `(4, 7)` из `U(0, 20)` и выполним линейную нормализацию вида `a*x+b` так, чтобы `min=0.0`, `max=1.0`.

In [2]:
import numpy as np

np.random.seed(42)  # фиксируем seed для воспроизводимости

arr = np.random.uniform(0, 20, size=(4, 7))

# Линейная нормализация в диапазон [0, 1]:
# x_norm = (x - x_min) / (x_max - x_min)
x_min, x_max = arr.min(), arr.max()
arr_norm = (arr - x_min) / (x_max - x_min)

arr, arr_norm.min(), arr_norm.max()


(array([[ 7.49080238, 19.01428613, 14.63987884, 11.97316968,  3.12037281,
          3.11989041,  1.16167224],
        [17.32352292, 12.02230023, 14.16145156,  0.41168989, 19.39819704,
         16.64885282,  4.24678221],
        [ 3.63649934,  3.6680902 ,  6.08484486, 10.49512863,  8.63890037,
          5.8245828 , 12.23705789],
        [ 2.78987721,  5.84289297,  7.32723687,  9.12139968, 15.70351923,
          3.99347564, 10.28468877]]),
 np.float64(0.0),
 np.float64(1.0))

## Разминка 2
Создадим матрицу `8×10` из целых чисел `[0, 10]` и найдем индекс строки с минимальной суммой элементов (и саму строку).

In [3]:
mat = np.random.randint(0, 11, size=(8, 10))  # верхняя граница не включается, поэтому 11
row_sums = mat.sum(axis=1)

min_row_idx = np.argmin(row_sums)
min_row = mat[min_row_idx]

mat, row_sums, min_row_idx, min_row


(array([[ 8,  2,  4,  2,  6,  4,  8,  6,  1,  3],
        [ 8,  1,  9,  8,  9,  4,  1,  3,  6,  7],
        [ 2,  0,  3,  1,  7,  3,  1,  5,  5,  9],
        [ 3,  5,  1,  9,  1,  9,  3,  7,  6,  8],
        [ 7,  4,  1,  4,  7,  9,  8,  8,  0,  8],
        [ 6,  8,  7,  0,  7,  7, 10,  2,  0,  7],
        [ 2,  2,  0, 10,  4,  9,  6,  9,  8,  6],
        [ 8,  7,  1,  0,  6,  6,  7,  4,  2,  7]]),
 array([44, 56, 36, 52, 56, 54, 56, 48]),
 np.int64(2),
 array([2, 0, 3, 1, 7, 3, 1, 5, 5, 9]))

## Разминка 3
Найдем евклидово расстояние между двумя одномерными векторами одинаковой размерности:  
\( d(x,y)=\sqrt{\sum_i (x_i-y_i)^2} \).

In [4]:
x = np.array([1.0, 2.0, 3.0, 4.0])
y = np.array([2.0, 0.0, 5.0, 1.0])

dist = np.linalg.norm(x - y)  # евклидова норма разности
dist


np.float64(4.242640687119285)

## Разминка 4
Решим матричное уравнение `A*X*B = -C`.

План:
1) Решаем `A*Y = -C` (получаем `Y`).
2) Решаем `X*B = Y` (получаем `X`).

Так избегаем явного вычисления обратных матриц.

In [5]:
A = np.array([[-1, 2, 4],
              [-3, 1, 2],
              [-3, 0, 1]], dtype=float)

B = np.array([[3, -1],
              [2,  1]], dtype=float)

C = np.array([[7, 21],
              [11, 8],
              [8,  4]], dtype=float)

# 1) A*Y = -C  => Y = solve(A, -C)
Y = np.linalg.solve(A, -C)

# 2) X*B = Y  => (B^T * X^T = Y^T) => X^T = solve(B^T, Y^T)
X = np.linalg.solve(B.T, Y.T).T

X


array([[ 1.00000000e+00,  3.99680289e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

In [6]:
# Проверка: A*X*B должно быть равно -C (с учетом численной погрешности)
np.allclose(A @ X @ B, -C)


True

## Лабораторная работа №1

### 1) Загрузка данных
Считаем файл в `numpy`-массив типа `int32` с помощью `np.loadtxt` и выведем первые 5 строк.

In [8]:
data = np.loadtxt(r"minutes_n_ingredients.csv", delimiter=",", skiprows=1, dtype=np.int32)

data[:5]


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

### 2) Среднее, минимум, максимум, медиана
Считаем статистики по каждому столбцу, кроме первого (`id`).

In [9]:
minutes = data[:, 1]
n_ing = data[:, 2]

stats = {
    "minutes": {
        "mean": minutes.mean(),
        "min": minutes.min(),
        "max": minutes.max(),
        "median": np.median(minutes),
    },
    "n_ingredients": {
        "mean": n_ing.mean(),
        "min": n_ing.min(),
        "max": n_ing.max(),
        "median": np.median(n_ing),
    }
}
stats


{'minutes': {'mean': np.float64(21601.00169),
  'min': np.int32(0),
  'max': np.int32(2147483647),
  'median': np.float64(40.0)},
 'n_ingredients': {'mean': np.float64(9.05528),
  'min': np.int32(1),
  'max': np.int32(39),
  'median': np.float64(9.0)}}

### 3) Ограничение сверху по квантилю $q_{0.75}$
Найдем квантиль `0.75` по `minutes` и «обрежем» значения сверху этим порогом.

Чтобы порог оставался целым (как и минуты), берем метод `higher` — возвращает значение из выборки.

In [10]:
q75 = np.quantile(minutes, 0.75, method="higher")

minutes_capped = np.minimum(minutes, q75).astype(np.int32)

q75, minutes.max(), minutes_capped.max()


(np.int32(65), np.int32(2147483647), np.int32(65))

In [11]:
data_capped = data.copy()
data_capped[:, 1] = minutes_capped
data_capped[:5]


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

### 4) Нулевые длительности
Посчитаем, сколько рецептов имеют `minutes = 0`, и заменим эти значения на `1` (чтобы избежать деления на ноль в дальнейших пунктах).

In [12]:
zero_mask = data_capped[:, 1] == 0
zero_count = int(zero_mask.sum())

data_fixed = data_capped.copy()
data_fixed[zero_mask, 1] = 1

zero_count, (data_fixed[:, 1] == 0).sum()


(479, np.int64(0))

### 5) Число уникальных рецептов
Посчитаем количество уникальных `id`.

In [14]:
unique_recipe_count = np.unique(data_fixed[:, 0]).size
unique_recipe_count


100000

### 6) Различные значения количества ингредиентов
Найдем все уникальные значения `n_ingredients` и их частоты.

In [15]:
vals, counts = np.unique(data_fixed[:, 2], return_counts=True)

# Покажем первые 15 пар (значение -> частота) и общее число различных значений
list(zip(vals[:15], counts[:15])), vals.size


([(np.int32(1), np.int64(13)),
  (np.int32(2), np.int64(926)),
  (np.int32(3), np.int64(2895)),
  (np.int32(4), np.int64(5515)),
  (np.int32(5), np.int64(7913)),
  (np.int32(6), np.int64(9376)),
  (np.int32(7), np.int64(10628)),
  (np.int32(8), np.int64(10951)),
  (np.int32(9), np.int64(10585)),
  (np.int32(10), np.int64(9591)),
  (np.int32(11), np.int64(8297)),
  (np.int32(12), np.int64(6605)),
  (np.int32(13), np.int64(4997)),
  (np.int32(14), np.int64(3663)),
  (np.int32(15), np.int64(2595))],
 37)

### 7) Рецепты не более чем с 5 ингредиентами
Отфильтруем строки, где `n_ingredients <= 5`.

In [16]:
data_le5 = data_fixed[data_fixed[:, 2] <= 5]
data_le5.shape, data_le5[:5]


((17262, 3),
 array([[446597,     15,      5],
        [204134,      5,      3],
        [ 25623,      6,      4],
        [484223,     18,      4],
        [ 63150,     65,      4]], dtype=int32))

### 8) Ингредиенты в минуту
Для каждого рецепта посчитаем отношение `n_ingredients / minutes` и найдем максимум по датасету.

In [17]:
ratio = data_fixed[:, 2] / data_fixed[:, 1]  # minutes уже >= 1
ratio_max = ratio.max()
ratio_max


np.float64(24.0)

### 9) Среднее число ингредиентов для топ-100 самых длинных рецептов
Отсортируем по `minutes` по убыванию и возьмем первые 100 строк.

In [ ]:
idx_sorted = np.argsort(data_fixed[:, 1])[::-1]
top100 = data_fixed[idx_sorted[:100]]

top100_mean_ing = top100[:, 2].mean()
top100_mean_ing


### 10) Случайные 10 различных рецептов
Выберем 10 уникальных `id` без повторений и выведем соответствующие строки.

In [18]:
rng = np.random.default_rng(42)

ids_unique = np.unique(data_fixed[:, 0])
sample_ids = rng.choice(ids_unique, size=10, replace=False)

# Для вывода найдем строки, соответствующие выбранным id (уникальный ключ)
sample_rows = np.vstack([data_fixed[data_fixed[:, 0] == rid][0] for rid in sample_ids])

sample_ids, sample_rows


(array([ 36423, 348155,  37702, 283215, 179482, 176744, 305431,  39626,
         81379, 398827], dtype=int32),
 array([[ 36423,     65,      5],
        [348155,     10,      6],
        [ 37702,     65,     12],
        [283215,     30,      7],
        [179482,      5,      6],
        [176744,     35,      9],
        [305431,     65,     12],
        [ 39626,     65,     19],
        [ 81379,     10,      7],
        [398827,     45,     18]], dtype=int32))

### 11) Процент рецептов с ингредиентами ниже среднего
Считаем долю строк, где `n_ingredients` меньше среднего по столбцу.

In [19]:
mean_ing = data_fixed[:, 2].mean()
pct_below_mean = 100.0 * (data_fixed[:, 2] < mean_ing).mean()

mean_ing, pct_below_mean


(np.float64(9.05528), np.float64(58.802))

### 12) Признак «простой» рецепт
Добавим столбец: `1`, если `minutes <= 20` и `n_ingredients <= 5`, иначе `0`.

In [20]:
simple = ((data_fixed[:, 1] <= 20) & (data_fixed[:, 2] <= 5)).astype(np.int32)

data_with_simple = np.column_stack([data_fixed, simple])  # добавляем новый столбец
data_with_simple[:5]


array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       [ 67660,      5,      6,      0],
       [157911,     60,     14,      0]], dtype=int32)

### 13) Процент «простых» рецептов
Посчитаем долю строк, у которых признак равен 1.

In [21]:
pct_simple = 100.0 * data_with_simple[:, 3].mean()
pct_simple


np.float64(9.552)

### 14) Группировка по длительности и формирование 3D массива
Группы:
- **короткие**: `< 10` минут
- **стандартные**: `10 <= minutes < 20` минут (включили 10, чтобы все значения попали в одну из групп)
- **длинные**: `>= 20` минут

Далее берём одинаковое число рецептов из каждой группы (минимум по размерам групп), чтобы можно было собрать единый 3D массив.

In [22]:
m = data_with_simple[:, 1]

short = data_with_simple[m < 10]
standard = data_with_simple[(m >= 10) & (m < 20)]
long = data_with_simple[m >= 20]

short.shape, standard.shape, long.shape


((7588, 4), (12661, 4), (79751, 4))

In [23]:
min_n = min(short.shape[0], standard.shape[0], long.shape[0])

arr_3d = np.stack([short[:min_n], standard[:min_n], long[:min_n]], axis=0)

arr_3d.shape


(3, 7588, 4)